export type Category="All"|"Beds"|"Sofas"|"Dining"|"Storage"|"Accents";
export type Product={id:string;name:string;category:Exclude<Category,"All">;price:number;regular:number;size:string;material:string;finish:string;tag:string;image:string;description:string;features:string[];source:string};
const asset=(name:string)=>`https://kinwud.com/static/img/${name}?v=21789202369`;
export const products:Product[]=[
{id:"meridian",name:"Meridian King Bed",category:"Beds",price:33200,regular:36900,size:"78 × 72 in",material:"Furniture construction",finish:"Walnut + antique brass",tag:"Richa / Kinwud",image:asset("bed-king-gold-inlay-headboard.jpg"),description:"Walnut laminate king bed with antique brass inlay.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"},
{id:"solace",name:"Solace King Bed",category:"Beds",price:32400,regular:36900,size:"78 × 72 in",material:"Furniture construction",finish:"Espresso walnut + brass",tag:"Richa / Kinwud",image:asset("bed-king-chevron-upholstered-headboard.jpg"),description:"Espresso walnut king bed with chevron upholstered headboard and brass detail.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"},
{id:"cascade",name:"Cascade King Storage Bed",category:"Beds",price:26700,regular:31500,size:"78 × 72 in",material:"Furniture construction",finish:"Espresso walnut & ivory oak",tag:"Richa / Kinwud",image:asset("bed-king-storage-ivory-panel.jpg"),description:"King storage bed in espresso walnut and ivory oak laminate.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"},
{id:"trellis",name:"Trellis King Storage Bed",category:"Beds",price:26700,regular:31500,size:"78 × 72 in",material:"Furniture construction",finish:"Espresso walnut & ivory oak",tag:"Richa / Kinwud",image:asset("bed-king-storage-diamond-motif.jpg"),description:"King storage bed with diamond motif headboard.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"},
{id:"mosaic",name:"Mosaic King Storage Bed",category:"Beds",price:19800,regular:22500,size:"78 × 72 in",material:"Furniture construction",finish:"Espresso walnut & ivory oak",tag:"Richa / Kinwud",image:asset("bed-king-storage-mosaic-headboard.jpg"),description:"King storage bed with mosaic headboard.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"},
{id:"rivena",name:"Rivena King Storage Bed",category:"Beds",price:19300,regular:21500,size:"78 × 72 in",material:"Furniture construction",finish:"Espresso walnut & ivory oak",tag:"Richa / Kinwud",image:asset("bed-king-storage-slat-headboard.jpg"),description:"King storage bed with slat headboard.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"},
{id:"ashira",name:"Ashira King Bed",category:"Beds",price:29300,regular:33400,size:"78 × 72 in",material:"Furniture construction",finish:"Ivory oak & wenge",tag:"Richa / Kinwud",image:asset("bed-king-ivory-lattice-headboard.jpg"),description:"King bed in ivory oak and wenge laminate.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"},
{id:"dune",name:"Dune King Bed",category:"Beds",price:40900,regular:45500,size:"78 × 72 in",material:"Furniture construction",finish:"Ivory & wenge",tag:"Richa / Kinwud",image:asset("bed-king-curved-ivory-headboard.jpg"),description:"Curved king bed with ivory and wenge PU finish.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"},
{id:"havelock",name:"Havelock Corner Sectional",category:"Sofas",price:70900,regular:83500,size:"112 × 88 in + ottoman & 2 stools",material:"Furniture construction",finish:"Tan distressed leatherette",tag:"Richa / Kinwud",image:asset("sofa-sectional-tan-leatherette.jpg"),description:"Corner sectional in tan distressed leatherette.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"},
{id:"marisol",name:"Marisol U-Sectional",category:"Sofas",price:70900,regular:83500,size:"124 × 92 in + ottoman & 2 stools",material:"Furniture construction",finish:"Teal crushed velvet",tag:"Richa / Kinwud",image:asset("sofa-sectional-teal-velvet.jpg"),description:"U-sectional in teal crushed velvet with polished chrome legs.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"},
{id:"aurelia",name:"Aurelia Curved Sectional",category:"Sofas",price:87000,regular:98900,size:"Sectional",material:"Furniture construction",finish:"Champagne printed fabric",tag:"Richa / Kinwud",image:asset("sofa-sectional-beige-tufted.jpg"),description:"Curved sectional in champagne printed fabric.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"},
{id:"regalia",name:"Regalia 3+1+1 Sofa Set",category:"Sofas",price:31900,regular:35500,size:"3+1+1",material:"Furniture construction",finish:"Maroon damask + rosewood",tag:"Richa / Kinwud",image:asset("sofa-set-3-1-1-maroon-wooden-arm.jpg"),description:"Classic 3+1+1 sofa set in maroon damask with rosewood polish.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"},
{id:"colonna",name:"Colonna 3+1+1 Sofa Set",category:"Sofas",price:43500,regular:49500,size:"3+1+1",material:"Furniture construction",finish:"Mocha suede + espresso lacquer",tag:"Richa / Kinwud",image:asset("sofa-set-3-1-1-channel-tufted-mocha.jpg"),description:"3+1+1 sofa set in mocha suede with channel tufting.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"},
{id:"heritage",name:"Heritage Dining Set",category:"Dining",price:62500,regular:69500,size:"6 seater",material:"Furniture construction",finish:"Honey teak + grey upholstery",tag:"Richa / Kinwud",image:asset("dining-set-6-seater-marble-carved-chairs.jpg"),description:"Six-seater dining set in honey teak polish with grey upholstery.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"},
{id:"lyra",name:"Lyra Dining Set",category:"Dining",price:55800,regular:63500,size:"6 seater",material:"Furniture construction",finish:"Honey teak + grey upholstery",tag:"Richa / Kinwud",image:asset("dining-set-6-seater-marble-scroll-chairs.jpg"),description:"Six-seater dining set in honey teak polish with grey upholstery.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"},
{id:"verona",name:"Verona Dining Set",category:"Dining",price:52200,regular:61500,size:"6 seater",material:"Furniture construction",finish:"Honey teak + grey upholstery",tag:"Richa / Kinwud",image:asset("dining-set-6-seater-marble-slat-chairs.jpg"),description:"Six-seater dining set in honey teak polish with grey upholstery.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"},
{id:"fortis",name:"Fortis 3-Door Wardrobe",category:"Storage",price:19300,regular:21500,size:"3 door",material:"Furniture construction",finish:"Deep walnut textured laminate",tag:"Richa / Kinwud",image:asset("wardrobe-3-door-walnut.jpg"),description:"Three-door wardrobe in deep walnut textured laminate.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"},
{id:"elara",name:"Elara Dresser with Mirror",category:"Storage",price:18000,regular:20500,size:"Dresser",material:"Furniture construction",finish:"Espresso rosewood",tag:"Richa / Kinwud",image:asset("dresser-tall-mirror-espresso.jpg"),description:"Tall dresser with mirror in espresso rosewood.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"},
{id:"lumen",name:"Lumen Dressing Table",category:"Storage",price:7200,regular:8500,size:"Dressing table",material:"Furniture construction",finish:"Wenge & ivory oak",tag:"Richa / Kinwud",image:asset("dressing-table-mirror-walnut.jpg"),description:"Dressing table with mirror in wenge and ivory oak.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"},
{id:"onyx",name:"Onyx Sideboard",category:"Storage",price:13000,regular:14500,size:"Sideboard",material:"Furniture construction",finish:"Rosewood & onyx glass",tag:"Richa / Kinwud",image:asset("sideboard-rosewood-black-glass.jpg"),description:"Sideboard combining rosewood with dark onyx glass.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"},
{id:"scholar",name:"Scholar Study Desk",category:"Storage",price:7200,regular:8500,size:"48 × 52 × 20 in",material:"Furniture construction",finish:"Walnut & ivory oak",tag:"Richa / Kinwud",image:asset("study-desk-hutch-walnut.jpg"),description:"Study desk with removable hutch in walnut and ivory oak.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"},
{id:"rosewell",name:"Rosewell Chaise Lounge",category:"Accents",price:22400,regular:25500,size:"72 × 30 × 34 in",material:"Furniture construction",finish:"Burgundy velvet",tag:"Richa / Kinwud",image:asset("chaise-lounge-burgundy-velvet.jpg"),description:"Chaise lounge in burgundy velvet with brass-tipped legs.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"},
{id:"coronet",name:"Coronet Accent Chair",category:"Accents",price:9400,regular:10500,size:"28 × 30 × 44 in",material:"Furniture construction",finish:"Mocha suede + walnut",tag:"Richa / Kinwud",image:asset("accent-chair-carved-crown-mocha.jpg"),description:"Accent chair in mocha suede with walnut polish.",features:["See showroom","Finish samples available","Made to order where applicable"],source:"Public Kinwud catalogue"}
];
export const categories:Category[]=["All","Beds","Sofas","Dining","Storage","Accents"];
export const finishes=[{name:"Espresso Walnut",value:"#4a3529"},{name:"Ivory Oak",value:"#d9c8a8"},{name:"Honey Teak",value:"#9a6a42"},{name:"Mocha",value:"#6a5042"},{name:"Teal Velvet",value:"#356b68"},{name:"Champagne",value:"#c5ae92"}];
export const showroom={name:"Richa Furniture",address:"Sunita Heights, Supriya Cinema Road, Mirza Tola Road, Bettiah, Bihar 845438",phone:"+91 88779 27486",hours:"10:00 — 20:00 daily",maps:"Richa Furniture, Sunita Heights, Supriya Cinema Road, Bettiah, Bihar 845438",storeImage:asset("store-img/richa-furniture-bettiah.jpg"),source:"Public Kinwud / Richa catalogue"};
